version: '3'
services:
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nba_api
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  webserver:
    image: puckel/docker-airflow:1.10.1
    restart: unless-stopped
    depends_on:
        - postgres
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.1
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3        
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
      - AIRFLOW_CONN_MEETUP=postgres://${DB_USER}:${PW}@${HOST}:${PORT}/${DB}
    volumes:
      - ./examples/intro-example/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
        image: shuixili/nba_airflow
        restart: unless-stopped
        depends_on:
            - webserver
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_MEETUP=postgres://${DB_USER}:${PW}@${HOST}:${PORT}/${DB}
            - FERNET_KEY=${FERNET_KEY}
        volumes:
            - ./dags:/usr/local/airflow/dags
        command: scheduler