CREATE USER postgres;
ALTER USER postgres with encrypted password 'postgres';
CREATE DATABASE postgres;
CREATE SCHEMA nba_api;

GRANT ALL PRIVILEGES ON DATABASE postgres TO postgres;

CREATE TABLE shotchartdetail (
	PRIMARY KEY(GAME_ID, PLAYER_ID, PERIOD, MINUTES_REMAINING, SECONDS_REMAINING, EVENT_TYPE, ACTION_TYPE, SHOT_TYPE),
	GRID_TYPE 	VARCHAR(100), 
	GAME_ID 	INTEGER,
	GAME_EVENT_ID	INTEGER,
	PLAYER_ID		INTEGER,
	PLAYER_NAME		VARCHAR(100), 
	TEAM_ID			INTEGER,
	TEAM_NAME		VARCHAR(100),
	PERIOD			INTEGER,
	MINUTES_REMAINING		INTEGER,
	SECONDS_REMAINING		INTEGER,
	EVENT_TYPE		VARCHAR(100),
	ACTION_TYPE		VARCHAR(100),
	SHOT_TYPE		VARCHAR(100),
	SHOT_ZONE_BASIC		VARCHAR(100),
	SHOT_ZONE_AREA		VARCHAR(100),
	SHOT_ZONE_RANGE		VARCHAR(100),
	SHOT_DISTANCE		INTEGER,
	LOC_X			INTEGER,
	LOC_Y			INTEGER,
	SHOT_ATTEMPTED_FLAG		INTEGER,
	SHOT_MADE_FLAG			INTEGER,
	GAME_DATE			VARCHAR(100),
	HTM			VARCHAR(100),
	VTM			VARCHAR(100) 
);


CREATE TABLE playercareerstats (
	PLAYER_ID INTEGER,
	SEASON_ID VARCHAR(100), 
	LEAGUE_ID INTEGER,
	TEAM_ID INTEGER,
	TEAM_ABBREVIATION VARCHAR(100) ,
	PLAYER_AGE INTEGER,
	GP INTEGER,
	GS INTEGER,
	MIN INTEGER,
	FGM INTEGER,
	FGA INTEGER,
	FG_PCT INTEGER,
	FG3M INTEGER,
	FG3A INTEGER,
	FG3_PCT INTEGER,
	FTM INTEGER,
	FTA INTEGER,
	FT_PCT INTEGER,
	OREB INTEGER,
	DREB INTEGER,
	REB INTEGER,
	AST INTEGER,
	STL INTEGER,
	BLK INTEGER,
	TOV INTEGER,
	PF INTEGER,
	PTS INTEGER
);


CREATE TABLE teams (
ID           INTEGER, 
FULL_NAME    VARCHAR(100),    
ABBREVIATION VARCHAR(100),    
NICKNAME     VARCHAR(100),    
CITY         VARCHAR(100),    
STATE        VARCHAR(100),    
YEAR_FOUNDED INTEGER 
);


create table roster(
teamid      integer,
season      integer,
leagueid    integer,
num         integer,
position    VARCHAR(100),   
height      VARCHAR(100),   
weight      integer,
birth_date  date   
age         integer,
school      VARCHAR(100),   
playerid    integer,
player      VARCHAR(100),   
exp         VARCHAR(100)
);


